### PR TITLE
fixed phpdocs, added phpstan config

### PR DESCRIPTION
**Pull request by clxmstaab**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
These phpdoc fixes (where relevant) should probably go into 1.x?

**Comment by stof** [comment]
I agree with @GrahamCampbell

**Comment by Seldaek** [comment]
Thanks @clxmstaab - I backported your commit to 1.x branch and updated phpstan fixes to latest master

**Comment by clxmstaab** [comment]
thanks!

**Pull request closed without merging**
