### PR TITLE
Added support for dates with format `Ymd.minor.patch`

### LINKED ISSUE #32: VersionParser throws UnexpectedValueException on 20150920.0.0
Composer unable to install google-closure-compiler package with the composer-asset-plugin due to a version number parsing issue. I'm trying to install the npm packages of Angular2, but it seems that the VersionParser class thinks the version number of the package (20150920.0.0) is invalid. Looks to me the check is too strict in that it only allows the major version to be up to five digits, but just changing the check makes a date-based version string fail a phpunit test, so I wasn't quite sure how this should be handled.

Here's a minimal compos er.json to reproduce the problem:

```
{
    "require": {
        "npm-asset/google-closure-compiler": "20150920.0.0"
    }
}
```

composer -vvv update output:

```
composer -vvv update
Reading ./composer.json
Loading config file /Users/ere/.composer/config.json
Loading config file /Users/ere/.composer/auth.json
Loading config file ./composer.json
Executing command (/Users/ere/src/composertest): git describe --exact-match --tags
Executing command (/Users/ere/src/composertest): git branch --no-color --no-abbrev -v
Executing command (/Users/ere/src/composertest): hg branch
Executing command (/Users/ere/src/composertest): svn info --xml
Reading ./composer.json
Loading config file /Users/ere/.composer/config.json
Loading config file /Users/ere/.composer/auth.json
Loading config file ./composer.json
Executing command (/Users/ere/src/composertest): git describe --exact-match --tags
Executing command (/Users/ere/src/composertest): git branch --no-color --no-abbrev -v
Executing command (/Users/ere/src/composertest): hg branch
Executing command (/Users/ere/src/composertest): svn info --xml



  [UnexpectedValueException]
  Could not parse version constraint 20150920.0.0: Invalid version string "20150920.0.0"



Exception trace:
 () at phar:///usr/local/bin/composer/vendor/composer/semver/src/VersionParser.php:467
 Composer\Semver\VersionParser->parseConstraint() at phar:///usr/local/bin/composer/vendor/composer/semver/src/VersionParser.php:248
 Composer\Semver\VersionParser->parseConstraints() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:234
 Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:124
 Composer\Package\Loader\ArrayLoader->load() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/RootPackageLoader.php:86
 Composer\Package\Loader\RootPackageLoader->load() at phar:///usr/local/bin/composer/src/Composer/Factory.php:284
 Composer\Factory->createComposer() at phar:///usr/local/bin/composer/src/Composer/Factory.php:504
 Composer\Factory::create() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/Command.php:53
 Composer\Command\Command->getComposer() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:88
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:841
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:167
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:98
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--] [<packages>]...
```

### PR DESCRIPTION
**Pull request by nazar-pc**
Works identical to `major.minor.patch`.
Fixes #32, https://github.com/fxpio/composer-asset-plugin/issues/185

### CODE REVIEW

**Comment by nazar-pc** [comment]
Can anyone look at this simple PR?

**Comment by alcohol** [comment]
I am not sure if we want to keep adding more version formats. We already support semver plus a wide range of exotic less used formats. If we add every format everyone comes up with, soon a version won't carry any meaning anymore.

**Comment by nazar-pc** [comment]
This is basically improving support for regular `major.minor.patch`, since `major` component is currently limited to 5 characters.

**Comment by alcohol** [comment]
It is limited explicitly to 5 so that it does not overlap with the date(time) regex.

**Comment by nazar-pc** [comment]
I know, but sometimes we might need to support 6 digits like in linked issues, so why not?

**Comment by alcohol** [comment]
Well, that is open to discussion. As mentioned in #32, we are not really convinced that this needs fixing.

@Seldaek is it easy to determine what the impact of this might be on the Packagist database?

**Comment by Seldaek** [comment]
No it's not easy to tell what the impact would be.. and since it just is to support an external package versioning scheme that isn't even PHP, I would tend to say it's not really our problem. The assets install plugin should make sure it provides valid version identifiers to Composer. Should be as easy as replacing dots by dashes if you see a large version number that looks like a date?

**Pull request closed without merging**
