### PR TITLE
travis: use container based build

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by alcohol** [comment]
Thanks.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by localheinz** [comment]
@TomasVotruba 

Just as an FYI, builds were already implicitly running on container-based infrastructure, see https://travis-ci.org/composer/semver/jobs/71392653.

Also see http://docs.travis-ci.com/user/workers/container-based-infrastructure/#Routing-your-build-to-container-based-infrastructure:

> The default behavior, when no `sudo` usage is detected in any customizable build phases, depends on the date when the repository is first recognized by Travis CI:

>* For repos we recognize before 2015-01-01, linux builds are sent to our standard infrastructure.
>* For repos we recognize on or after 2015-01-01, linux builds are sent to our container-based infrastructure.

**Comment by TomasVotruba** [comment]
@localheinz I know about this dating. That's kinda strange, because this repo was established in 2011.

**Comment by alcohol** [comment]
@TomasVotruba No actually it was created this month. But the history dates back further because it was exported from [composer/composer](/composer/composer).

**Comment by TomasVotruba** [comment]
@alcohol I see, interesting exception. Thanks for explaining :)

Shall I send removal PR? But I think it could be confusing for further devs as it was for me.

**Comment by alcohol** [comment]
No it's fine to have it in there anyway. It just makes it more explicit. No worries.

**Comment by TomasVotruba** [comment]
:+1:

**Comment by localheinz** [comment]
@TomasVotruba 

:+1:

**Pull request merged**
