### PR TITLE
fix invalid syntax in phpdoc

### PR DESCRIPTION
**Pull request by orklah**
Hi,

This PR fixes an extraneous bracket at the end of a phpdoc line.

Related to https://github.com/vimeo/psalm/issues/7289

### CODE REVIEW

**Comment by orklah** [comment]
@ondrejmirtes I'm surprised phpstan did not pick that up, this repo is on level 8

**Comment by Seldaek** [comment]
Indeed it is pretty lenient with extraneous characters, I suppose as long as it finished parsing a valid value it ignores what follows https://phpstan.org/r/27b3fb0e-1cb0-4b4d-9cd7-1e37a5ce260e

Anyway thanks for the fix

**Comment by orklah** [comment]
Thanks for merging!

> as long as it finished parsing a valid value it ignores what follows

Probably yeah, this must make this hard to debug though: https://phpstan.org/r/6a8372a5-0f20-4469-a134-0807a15d3e6c

**Comment by Seldaek** [comment]
True, I'd say please report this to phpstan that example makes a very good case for a need to fix it

**Pull request merged**
