### PR TITLE
contiguous range with exclusion is collapsed improperly #42

### PR DESCRIPTION
**Pull request by alcohol**
refs #42

### CODE REVIEW

**Comment by alcohol** [comment]
Second test case fails due to how the contiguous range is determined based on simple string comparison and it blindly assumes it can join the two together using just two constraints (lower and upper bound).

screenshot from 2016-08-24 13-17-41

**Comment by alcohol** [comment]
@Seldaek added two test related commits that hopefully clarify the issue more.

**Comment by alcohol** [comment]
Alternatively, I'm working on something that involves a lot more logic. It's an interesting challenge, but I'm not sure if the added overhead would be worth it. Regardless, it's fun to work on :p

**Comment by alcohol** [comment]
Rebased this PR to represent the simplest fix.

**Comment by bendavies** [comment]
although this fixes the issue, shouldn't the solver be able to parse the previously generated multi constraint? i.e. isn't this just working around a solver bug? @Seldaek ?

**Comment by stof** [comment]
@bendavies the previously generated multi constraint was wrong. This is not the solver job to fix mistakes of the constraint parser (the only change we could do in the solver would be to throw an exception when detecting such a broken constraint, but it would involve detecting them, which would add overhead to cater for a broken parser so not worth it).

**Comment by bendavies** [comment]
👍

**Comment by alcohol** [comment]
@Seldaek lets just merge this, my alternative take is kind of insane in comparison :p

**Pull request merged**
