### PR TITLE
Fix modifier parsing

### LINKED ISSUE #24: VersionParser only allows one numeric pre-release identifier
I released 0.1.0-beta.3 of my project yesterday. Unfortunately it contained a critical bug, so I fixed and proceeded to release 0.1.0-beta.3.1. From semver.org:

> 9. A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. [...] Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

Packagist wasn't picking up the tag for some reason. I investigated and traced the problem back to here (while I don't have hard proof that this is indeed the problem, this is what I *suspect* that it is).

I found that composer/composer's VcsRepository will [skip a tag if it doesn't validate](https://github.com/composer/composer/blob/master/src/Composer/Repository/VcsRepository.php#L147).

[Tag validation](https://github.com/composer/composer/blob/master/src/Composer/Repository/VcsRepository.php#L296) uses the VersionParser from composer/semver.

So I checked out VersionParser, and it seems that the [regex that matches the pre-release modifier](https://github.com/composer/semver/blob/master/src/VersionParser.php#L27) only allows one numeric pre-release identifier. i.e. it will match `0.1.0-beta.3`, but not `0.1.0-beta.3.1`.

Is there a good reason for this? Would it be possible to fix?

### PR DESCRIPTION
**Pull request by Seldaek**
Replaces #25 and fixes #24

### CODE REVIEW

**Comment by stof** [comment]
:+1:

**Comment by alcohol** [comment]
Ah, like so. That works quite well. :+1:

**Comment by stof** [comment]
There is still 1 point to check for them: is ``version_compare`` handling such versions properly ? This was the reason for the normalized_version in composer at first: version_compare was not comparing versions properly when they don't have the same number of segments

**Comment by alcohol** [comment]
We could add some tests to either `ComparatorTest` or `VersionParserTest` to make sure the behaviour is still as expected (if they aren't yet covered).

**Comment by stof** [comment]
@alcohol the cas of ``beta3.1`` is clearly not covered in these tests, as it was not supported before this PR

**Comment by alcohol** [comment]
That is why I said we could add some tests?

**Comment by Seldaek** [comment]
Added a bunch in https://github.com/composer/semver/commit/c18a6fb7492aa07b5961deda04d9718d383accfb - anything else you think need coverage?

**Comment by alcohol** [comment]
I think that covers most scenarios.

**Pull request merged**
