### PR TITLE
[WIP] Test on PHP 7.4 Stable

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks like we'll have to upgrade PHPUnit to test on PHP 7.4 properly.

**Comment by peter279k** [comment]
The Travis CI build is failed on `php-7.4` version.
The failed message is as follows:

```
1) Composer\Semver\Constraint\ConstraintTest::testInverseMatchingOtherConstraints
Function ReflectionType::__toString() is deprecated
```

According to this [PHPUnit issue](https://github.com/sebastianbergmann/phpunit/issues/3728), it seems that the `PHPUnit` should use `8.2.3` at least for `php-7.4` version.

It should define the PHPUnit `8.2.x` version on [composer.json](https://github.com/composer/semver/blob/master/composer.json#L37)

**Comment by GrahamCampbell** [comment]
@peter279k I know, but we can't "just update the version of phpunit". There is some work to do.

**Comment by peter279k** [comment]
> @peter279k I know, but we can't "just update the version of phpunit". There is some work to do.

I know that, and we should concern about new approaches and features for upgrading `PHPUnit` version :).

**Comment by GrahamCampbell** [comment]
You're welcome to finish off this PR if you'd like.

**Comment by GrahamCampbell** [comment]
If someone wants to take over here, and finish this, that would be good. I don't have the free time needed to finish this at the moment.

**Pull request closed without merging**
