### PR TITLE
Make sure the syntax is consistant

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by alcohol** [comment]
@seldaek would prefer to see `||` consistently instead of `|`. So if you don't mind.. :-)

**Comment by Seldaek** [comment]
Yeah || is the new cool, npm compatible and the only thing we recommend in docs https://getcomposer.org/doc/articles/versions.md#range

**Comment by vinkla** [comment]
Does `|` and `||` work differently? Will `|` be deprecated in the future?

**Comment by alcohol** [comment]
No and no.

**Comment by Seldaek** [comment]
@GrahamCampbell if you don't want to contribute you don't *have* to. Passive aggressive commit messages aren't needed, we talk with words in comments here if we have something to discuss.

**Comment by Seldaek** [comment]
Closed by 07b4f7727ca5558e85b20cde33cb2c24a342efb5

**Comment by vinkla** [comment]
@alcohol Okay, but it is recommended to use `||` instead of `|`?

**Comment by alcohol** [comment]
That is what @Seldaek just said, yes. Also you can see our documentation only refers to `||` if you follow the link he shared.

**Pull request closed without merging**
